/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  RX_Lab                                         */
/*      FILE         :  stacksct.h                                     */
/*      DESCRIPTION  :  Setting of Stack area                          */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  RX63N                                          */
/*  													               */
/*      This file is generated by e2studio.                        */
/*  													               */
/***********************************************************************/
#pragma stacksize su=0x1000
#pragma stacksize si=0x400
