/***********************************************************************/
/*  													               */
/*      PROJECT NAME :  RX_Lab                                         */
/*      FILE         :  vector_table.c                                 */
/*      DESCRIPTION  :  Vector Table                                   */
/*      CPU SERIES   :  RX600                                          */
/*      CPU TYPE     :  RX63N                                          */
/*  													               */
/*      This file is generated by e2studio.                        */
/*  													               */
/***********************************************************************/                                                                           
                                                                           
                                                                           
                                                                           
                                                                          
#include "vect.h"

 #pragma address id_code = 0xFFFFFFA0

 typedef unsigned int uint32_t;

 const uint32_t id_code[4] =
 {
         0xFFFFFFFF,
         0xFFFFFFFF,
         0xFFFFFFFF,
         0xFFFFFFFF,
 };

#pragma section C FIXEDVECT

void (*const Fixed_Vectors[])(void) =
{
//;0xffffffd0  Exception(Supervisor Instruction)
    Excep_SuperVisorInst,
//;0xffffffd4  Reserved
    Dummy,
//;0xffffffd8  Reserved
    Dummy,
//;0xffffffdc  Exception(Undefined Instruction)
    Excep_UndefinedInst,
//;0xffffffe0  Reserved
    Dummy,
//;0xffffffe4  Exception(Floating Point)
    Excep_FloatingPoint,
//;0xffffffe8  Reserved
    Dummy,
//;0xffffffec  Reserved
    Dummy,
//;0xfffffff0  Reserved
    Dummy,
//;0xfffffff4  Reserved
    Dummy,
//;0xfffffff8  NMI
    NonMaskableInterrupt,
//;0xfffffffc  RESET
//;<<VECTOR DATA START (POWER ON RESET)>>
//;Power On Reset PC
   PowerON_Reset                                                                                                                 
//;<<VECTOR DATA END (POWER ON RESET)>>
};

#pragma address MDEreg=0xffffff80 // MDE register (Single Chip Mode)
#ifdef __BIG
	const unsigned long MDEreg = 0xfffffff8; // big
#else
	const unsigned long MDEreg = 0xffffffff; // little
#endif
